---

- hosts: default
  remote_user: root

  tasks:

  - name: install NGinX
    community.general.apk:
      name: nginx
      state: present
      update_cache: yes

  - name: start NGinX
    ansible.builtin.service:
      name: nginx
      state: started

  - name: install servers to NGinX
    template:
      src: nginx_server.j2
      dest: /etc/nginx/http.d/{{ item }}.conf
      owner: root
      group: root
      mode: "0644"
    loop: "{{ alias_domains }}"
    register: template_result

  - name: reload NGinx configuration
    ansible.builtin.service:
      name: nginx
      state: 
    when: template_result is changed

